-- I did what I could with the time I had.



--2.1.1 1
SELECT * FROM EMPLOYEE;

--2.1.2 2
SELECT * FROM EMPLOYEE
WHERE LASTNAME = 'King';

--2.1.3 3
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME = 'Andrew' 
AND REPORTSTO IS NULL;



--2.2.1 4
SELECT * FROM ALBUM
ORDER BY TITLE DESC ;

--2.2.2 5
SELECT FIRSTNAME FROM CUSTOMER
ORDER BY CITY ASC;

--2.3.1 6
INSERT INTO GENRE
VALUES (26, 'Techno-Pop');

INSERT INTO GENRE
VALUES (27, 'Lofi-Pop');

--2.3.2 7
INSERT INTO EMPLOYEE
VALUES(9,'Miller','John', 'Sales Manager','3','17-MAR-94','12-FEB-10','1415 Fairlane Dr.','Joplin','MO','U.S.','64093','1 (417)(436)(3456)','1 (404) 432-2345','miller@chinookcorp.com');

INSERT INTO EMPLOYEE
VALUES(10,'Miller','Justine', 'CEO','10','17-JUN-95','12-FEB-05','1415 Fairlane Dr.','Joplin','MO','U.S.','64093','1 (417)(437)(3546)','1 (404) 432-2345','millerCEO@chinookcorp.com');


--2.3.3 8 
SELECT * FROM CUSTOMER;

INSERT INTO CUSTOMER
VALUES(60,'Geroge','Foreman',null,'614 Washington Street', 'Los Angeles', 'CA', 'U.S', '65012','(123) 322-4365',null,'fourmen@andagrill.com',5);

INSERT INTO CUSTOMER
VALUES(61,'Jennifer' , 'Antidaughter', null, '1414 Dark Street', 'Las Vegas', 'FL', 'U.S.', '23433', '(435) 986-3491', null , 'allme@me.com',2);



--2.4.1 9
UPDATE CUSTOMER 
set FIRSTNAME = 'Robert',
LASTNAME = 'Walter'
WHERE FIRSTNAME = 'Robert'
AND LASTNAME = 'Wlter';

-- 2.4.2 10
UPDATE ARTIST
SET NAME = 'CCR'
WHERE NAME = 'Creedence Clearwater Revival';


--2.5.1 11
SELECT * FROM INVOICE
WHERE BILLINGADDRESS LIKE 'T%';


--2.6.1 12
SELECT * FROM INVOICE
WHERE TOTAL > 15
AND TOTAL <50;

--2.6.2 13
--Skipped for now


--2.7.1 14
DELETE INVOICELINE
WHERE INVOICEID = ANY (SELECT INVOICEID FROM INVOICE
                    WHERE (SELECT CUSTOMERID FROM CUSTOMER
        WHERE FIRSTNAME = 'Robert'
        AND LASTNAME = 'Walter') = CUSTOMERID);



DELETE INVOICE
WHERE (SELECT CUSTOMERID FROM CUSTOMER
        WHERE FIRSTNAME = 'Robert'
        AND LASTNAME = 'Walter') = CUSTOMERID;
        
DELETE CUSTOMER 
        WHERE FIRSTNAME = 'Robert'
        AND LASTNAME = 'Walter';
        
        
-- 3.1.1 15

CREATE OR REPLACE FUNCTION GET_DATE
RETURN VARCHAR2 AS THE_DATE VARCHAR(30);
BEGIN
SELECT TO_CHAR(SYSDATE, 'HH24:MI:SS')
INTO THE_DATE
FROM DUAL;
RETURN THE_DATE;
END;
/

--3.1.2

CREATE OR REPLACE FUNCTION MED_LENGTH
RETURN VARCHAR IS MAXLENGTHTITLE VARCHAR(40);
BEGIN
SELECT NAME INTO MAXLENGTHTITLE FROM TRACK 
WHERE UNITPRICE = (SELECT UNITPRICE FROM TRACK
                    ORDER BY UNITPRICE DESC
                    FETCH FIRST)
                    ORDER BY DESC;
RETURN MAXLENGTHTITLE;
END MED_LENGTH;
/

--3.2.1 NOT WORKING YET
CREATE OR REPLACE FUNCTION GET_AVG(NUM IN INTEGER)
RETURN NUMBER IS BEGIN
RETURN SELECT AVG(TOTAL) FROM INVOICE ;
END;
/



-- 6.1.1

--Getting what I can done
--TRIGGER
CREATE OR REPLACE TRIGGER T
AFTER INSERT ON EMPLOYEE
BEGIN
DBMS_OUTPUT.PUT_LINE('FINISHED INSERTING');
END;
/

--6.1.2 After album creation Trigger
CREATE OR REPLACE TRIGGER T2
AFTER UPDATE ON ALBUM 
BEGIN
DBMS_OUTPUT.PUT_LINE('FINISHED UPDATING');
END;
/


--7.1.1 Inner Join
SELECT CUSTOMER.FIRSTNAME,CUSTOMER.LASTNAME, INVOICE.INVOICEID
FROM CUSTOMER
INNER JOIN INVOICE ON CUSTOMER.CUSTOMERID = INVOICE.CUSTOMERID;

