CREATE TABLE BANK_USER (
USER_ID INTEGER PRIMARY KEY,
FIRSTNAME VARCHAR2(30),
LASTNAME VARCHAR2(30),
USERNAME VARCHAR2(30),
PASS VARCHAR2(30),
USERTYPE_ID INTEGER
);

CREATE TABLE BANK_ACCOUNT (
ACCOUNT_ID INTEGER PRIMARY KEY,
USER_ID INTEGER,
USERNAME VARCHAR2(30),
ACCOUNT_BALANCE NUMBER(10,2),
FOREIGN KEY(USER_ID) REFERENCES BANK_USER(USER_ID)ON DELETE CASCADE
);


CREATE SEQUENCE USERSEQ;
CREATE SEQUENCE ACCOUNTSEQ;

CREATE OR REPLACE PROCEDURE DELETEUSER
(USERID IN INTEGER)
AS
BEGIN
    DELETE FROM BANK_USER WHERE USER_ID = USERID;
COMMIT;
END;
/

EXECUTE DELETEUSER(USERID);

CREATE OR REPLACE PROCEDURE DELETEACCOUNT
(USER_NAME IN VARCHAR2, ACCOUNTID IN INTEGER)
AS
BEGIN
    DELETE FROM BANK_ACCOUNT WHERE USERNAME = USER_NAME AND ACCOUNT_ID = ACCOUNTID;
COMMIT;
END;
/