CREATE SEQUENCE MYTESTSEQ
MINVALUE 600
MAXVALUE 900
INCREMENT BY 5
CACHE 5;

SELECT MYTESTSEQ.NEXTVAL FROM DUAL;

INSERT INTO STUDENT(MYSEQ.NEXTVAL, 'BOB');

CREATE VIEW MYVIEW
AS SELECT TITLE FROM ALBUM
UNION
SELECT NAME FROM ARTIST;

SELECT * FROM MYVIEW;