CREATE SEQUENCE MYTESTSEQ
MINVALUE 600
MAXVALUE 900
INCREMENT BY 5
CACHE 5; --Caches the next 5 sequence


SELECT MYTESTSEQ.NEXTVAL FROM DUAL;
/*
Sequence is used to do a certain function
MyTestSeq increments value by 5
INSERT INTO STUDENT(MyTestSeq.NEXTVAL, 'bob');
*/

-- A VIEW TO A KILL
CREATE VIEW MYVIEW
AS SELECT TITLE FROM ALBUM
UNION
SELECT NAME FROM ARTIST;

SELECT * FROM MYVIEW;


-- Functions
CREATE OR REPLACE FUNCTION CALC_TAX
    (T_ID IN NUMBER, TAX IN NUMBER)
    RETURN NUMBER AS 
    TOTAL_PRICE NUMBER(10,2);
    BEGIN
    SELECT UNITPRICE INTO TOTAL_PRICE
    FROM TRACK WHERE TRACKID = T_ID;
    RETURN TOTAL_PRICE + (TOTAL_PRICE * TAX);
    END; 
    /
    
SELECT CALC_TAX(2921,.06) FROM DUAL;

--STORED PROCEDURE
CREATE OR REPLACE PROCEDURE MYFAKEPRO
    (ID IN INT, NAME IN VARCHAR2)
    AS
    BEGIN
    INSERT INTO SCHOOL VALUES(MYSEQ.NEXTVAL,NAME);
    COMMIT;
    END;
    /
EXECUTE MYFAKEPRO('USF');
    
    
CREATE OR REPLACE PROCEDURE BEARPRO
    (CAVE_NAME IN VARCHAR2, BEAR_NAME IN VARCHAR2,
        BEAR_BIRTHDATE IN DATE, CAVE_ID AS NUMBER)
AS
BEGIN
INSERT INTO CAVE VALUES(MYSEQ.NEXTVAL,CAVE_NAME);
INSERT INTO BEEHIVE VALUES(MYSEQ.NEXTVAL,50);
INSERT INTO BEAR VALUES(MYSEQ.NEXTVAL,1,BEAR_NAME,BEAR_BIRTHDATE,
    200,CAVE_ID);
COMMIT
END;
/
EXECUTE BEARPRO('WOO''PERT',DATE '1999-02-15',1);

--FUNCTION 1
CREATE OR REPLACE FUNCTION ROLLTIDE
RETURN VARCHAR2 AS
BEGIN
RETURN 'ROLLTIDE';
END;
/
SELECT ROLLTIDE FROM DUAL;

CREATE OR REPLACE PROCEDURE ADDSTUFF
    (THEID in INT,FNAME IN VARCHAR(20),
    LNAME IN VARCHAR(20))
    AS
    BEGIN
    INSERT INTO SUNNY(MYTESTSEQ.NEXTVAL,FNAME,LNAME);
    COMMIT;
    END;
    /