--DROP TABLE USER_TRANSACTION;
--DROP TABLE BANK_ACCOUNT;
--DROP TABLE CUSTOMER_ACCOUNT;

CREATE TABLE CUSTOMER_ACCOUNT (
    USER_ID INTEGER PRIMARY KEY,
    USERNAME VARCHAR2(100) UNIQUE,
    PASSWORD VARCHAR2(100),
    FIRSTNAME VARCHAR2(100),
    LASTNAME VARCHAR2(100)
);

CREATE TABLE BANK_ACCOUNT (
    BANK_ACCOUNT_ID INTEGER PRIMARY KEY,
    BALANCE FLOAT DEFAULT 0.0,
    USER_ID INTEGER
);

CREATE TABLE USER_TRANSACTION (
    TRANSACTION_ID INTEGER PRIMARY KEY,
    USER_ID INTEGER,
    BANK_ACCOUNT_ID INTEGER,
    MESSAGE VARCHAR2(200)
);

ALTER TABLE USER_TRANSACTION
ADD CONSTRAINT FK_T_USER_ID
FOREIGN KEY (USER_ID) REFERENCES CUSTOMER_ACCOUNT(USER_ID);

ALTER TABLE USER_TRANSACTION 
ADD CONSTRAINT FK_T_BANK_ACCOUNT_ID
FOREIGN KEY (BANK_ACCOUNT_ID) REFERENCES BANK_ACCOUNT(BANK_ACCOUNT_ID);

ALTER TABLE BANK_ACCOUNT
ADD CONSTRAINT FK_USER_ID
FOREIGN KEY (USER_ID) REFERENCES CUSTOMER_ACCOUNT(USER_ID);

CREATE SEQUENCE USERSEQ
MINVALUE 1000
MAXVALUE 2000
INCREMENT BY 1
CACHE 5;

CREATE SEQUENCE BANKSEQ
MINVALUE 1000
MAXVALUE 2000
INCREMENT BY 1
CACHE 5;

CREATE SEQUENCE TRANSACTIONSEQ
MINVALUE 1000
MAXVALUE 2000
INCREMENT BY 1
CACHE 5;

--INSERT INTO CUSTOMER
CREATE OR REPLACE PROCEDURE INSERTCUSTOMER
(USERNAME IN VARCHAR2, PASSWORD IN VARCHAR2, 
FIRSTNAME IN VARCHAR2, LASTNAME IN VARCHAR2)
AS
BEGIN
    INSERT INTO CUSTOMER_ACCOUNT VALUES 
    (USERSEQ.NEXTVAL, USERNAME, PASSWORD, FIRSTNAME, LASTNAME);
    COMMIT;
END;
/

--DELETE FROM CUSTOMER
CREATE OR REPLACE PROCEDURE DELETECUSTOMER
(CUSTOMER_ID IN NUMBER)
AS
BEGIN
    DELETE FROM USER_TRANSACTION
    WHERE USER_ID = CUSTOMER_ID;
    DELETE FROM BANK_ACCOUNT
    WHERE USER_ID = CUSTOMER_ID;
    DELETE FROM CUSTOMER_ACCOUNT
    WHERE USER_ID = CUSTOMER_ID;
    COMMIT;
END;
/

--UPDATE CUSTOMER
CREATE OR REPLACE PROCEDURE UPDATECUSTOMER
(ID IN NUMBER, USER IN VARCHAR2, PASS IN VARCHAR2, 
FIRST IN VARCHAR2, LAST IN VARCHAR2)
AS
BEGIN
    UPDATE CUSTOMER_ACCOUNT
    SET USERNAME = USER, PASSWORD = PASS,
    FIRSTNAME = FIRST, LASTNAME = LAST 
    WHERE USER_ID = ID;
    COMMIT;
END;
/

--INSERT INTO BANK
CREATE OR REPLACE PROCEDURE INSERTBANK
(BALANCE IN FLOAT, USER_ID IN NUMBER)
AS
BEGIN
    INSERT INTO BANK_ACCOUNT VALUES 
    (BANKSEQ.NEXTVAL, BALANCE, USER_ID);
    COMMIT;
END;
/

--DELETE FROM BANK
CREATE OR REPLACE PROCEDURE DELETEBANK
(BANK_ID IN NUMBER)
AS
BEGIN
    DELETE FROM USER_TRANSACTION
    WHERE BANK_ACCOUNT_ID = BANK_ID;
    DELETE FROM BANK_ACCOUNT
    WHERE BANK_ID = BANK_ACCOUNT_ID;
    COMMIT;
END;
/

--UPDATE BANK
CREATE OR REPLACE PROCEDURE UPDATEBANK
(ID IN NUMBER, BAL IN FLOAT, UID IN NUMBER)
AS
BEGIN
    UPDATE BANK_ACCOUNT
    SET BALANCE = BAL, USER_ID = UID 
    WHERE BANK_ACCOUNT_ID = ID;
    COMMIT;
END;
/

--INSERT INTO USER_TRANSACTION
CREATE OR REPLACE PROCEDURE INSERTTRANSACTION
(UID IN NUMBER, BID IN NUMBER, MES IN VARCHAR2)
AS
BEGIN
    INSERT INTO USER_TRANSACTION VALUES 
    (TRANSACTIONSEQ.NEXTVAL, UID, BID, MES);
    COMMIT;
END;
/
