CREATE TABLE BANK_CUSTOMER
(USERNAME VARCHAR2(20),PASSWORD VARCHAR2 (20),FIRST_NAME VARCHAR2(20),
LAST_NAME VARCHAR2 (20),SOCIAL_SECURITY VARCHAR2 (20),AGE VARCHAR2(20),ADDRESS VARCHAR2(40),
CITY VARCHAR2 (20),STATE VARCHAR2(20),ZIPCODE VARCHAR2(20),PRIMARY KEY (USERNAME));


CREATE TABLE ACCOUNT
(ACCOUNTID INT, USERNAME VARCHAR (20),ACCOUNTTYPE VARCHAR2(20),ACCOUNTNAME VARCHAR2(20),BALANCE DECIMAL(20,2),PRIMARY KEY(ACCOUNTID));


CREATE OR REPLACE PROCEDURE INSERTBANKCUSTOMER


(USERNAME IN VARCHAR2,PASSWORD IN VARCHAR2 ,FIRST_NAME IN VARCHAR2,
LAST_NAME  IN VARCHAR2 ,SOCIAL_SECURITY IN VARCHAR2 ,AGE IN VARCHAR2,ADDRESS IN VARCHAR2,
CITY IN VARCHAR2,STATE IN VARCHAR2,ZIPCODE IN VARCHAR2)
AS 
BEGIN
INSERT INTO BANK_CUSTOMER VALUES( USERNAME,PASSWORD,FIRST_NAME,LAST_NAME,SOCIAL_SECURITY,AGE,ADDRESS,CITY,STATE,ZIPCODE);
COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE  UPDATEBANKCUSTOMER
(INUSERNAME IN VARCHAR2,INPASSWORD IN VARCHAR2 ,INFIRST_NAME IN VARCHAR2,
INLAST_NAME  IN VARCHAR2 ,INSOCIAL_SECURITY IN VARCHAR2 ,INAGE IN VARCHAR2,INADDRESS IN VARCHAR2,
INCITY IN VARCHAR2,INSTATE IN VARCHAR2,INZIPCODE IN VARCHAR2)
AS 
BEGIN
UPDATE BANK_CUSTOMER
SET


BANK_CUSTOMER.PASSWORD = INPASSWORD,
BANK_CUSTOMER.FIRST_NAME= INFIRST_NAME,
BANK_CUSTOMER.LAST_NAME = INLAST_NAME,
BANK_CUSTOMER.SOCIAL_SECURITY = INSOCIAL_SECURITY,
BANK_CUSTOMER.AGE=INAGE,
BANK_CUSTOMER.ADDRESS = INADDRESS,
BANK_CUSTOMER.CITY=INCITY,
BANK_CUSTOMER.STATE=INSTATE,
BANK_CUSTOMER.ZIPCODE=INZIPCODE
WHERE BANK_CUSTOMER.USERNAME=INUSERNAME;
COMMIT;
END;
/

INSERT INTO BANK_CUSTOMER (USERNAME, PASSWORD) VALUES ( 'MARC123','PASSWORD');
COMMIT;

INSERT INTO ACCOUNT (ACCOUNTID,USERNAME,ACCOUNTTYPE,ACCOUNTNAME,BALANCE) VALUES (1200,'edwin123','CHECKINGS','',25);
COMMIT;

CREATE OR REPLACE PROCEDURE INSERTACCOUNT
(ACCOUNTID INT, USERNAME VARCHAR2,ACCOUNTTYPE VARCHAR2,ACCOUNTNAME VARCHAR2,BALANCE DECIMAL)
AS 
BEGIN
INSERT INTO ACCOUNT VALUES(GENERATE_ACCOUNTNUM.NEXTVAL,USERNAME,ACCOUNTTYPE,ACCOUNTNAME,BALANCE);
COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATEACCOUNT
(INACCOUNTID IN INT, INUSERNAME IN VARCHAR2,INACCOUNTTYPE IN VARCHAR2,INACCOUNTNAME IN VARCHAR2,INBALANCE IN DECIMAL)
AS
BEGIN
UPDATE ACCOUNT
SET
--ACCOUNT.ACCOUNTID = INACCOUNT,
ACCOUNT.USERNAME =INUSERNAME,
ACCOUNT.ACCOUNTTYPE=INACCOUNTTYPE,
ACCOUNT.ACCOUNTNAME=INACCOUNTNAME,
ACCOUNT.BALANCE=INBALANCE
WHERE ACCOUNT.ACCOUNTID=INACCOUNTID;
COMMIT;
END;
/

CREATE SEQUENCE GENERATE_ACCOUNTNUM
MINVALUE 1000
MAXVALUE 4000
START WITH 1000
INCREMENT BY 1
CACHE 5;

