CREATE TABLE BANKACCOUNT(
ACCOUNTNUMBER INTEGER PRIMARY KEY,
BALANCE DECIMAL(30,4),
FIRSTOWNERSLOGINNAME VARCHAR2(14),
SECONDOWNERSLOGINNAME VARCHAR2(14),
FIRSTOWNERSFULLNAME VARCHAR(30),
SECONDOWNERSFULLNAME VARCHAR(30),
ACCOUNTTYPE VARCHAR(30),
ACCOUNTSTATUS VARCHAR(30),
JOINTOWNER VARCHAR(30)
);

CREATE OR REPLACE PROCEDURE INSERTBANKACCOUNT
(ACCNUM IN INTEGER, 
BALANCE IN DECIMAL, 
FIRSTOWNERSID IN VARCHAR2, 
SECONDOWNERSID IN VARCHAR2,
FIRSTOWNERSNAME IN VARCHAR2,
SECONDOWNERSNAME IN VARCHAR2,
ACCTYPE IN VARCHAR2,
STATUS IN VARCHAR2,
JOINT IN VARCHAR2)
AS
BEGIN
INSERT INTO BANKACCOUNT VALUES(ACC_NUM_GEN.NEXTVAL, BALANCE, 
FIRSTOWNERSID, SECONDOWNERSID, 
FIRSTOWNERSNAME, SECONDOWNERSNAME, 
ACCTYPE, STATUS, JOINT);
COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATEBANKACCOUNT
(ACCNUM IN INTEGER, 
FIRSTOWNERSID IN VARCHAR2, 
SECONDOWNERSID IN VARCHAR2,
FIRSTOWNERSNAME IN VARCHAR2,
SECONDOWNERSNAME IN VARCHAR2,
ACCTYPE IN VARCHAR2,
STATUS IN VARCHAR2,
JOINT IN VARCHAR2)
AS
BEGIN
UPDATE BANKACCOUNT
SET 
BANKACCOUNT.FIRSTOWNERSLOGINNAME = FIRSTOWNERSID,
BANKACCOUNT.SECONDOWNERSLOGINNAME = SECONDOWNERSID,
BANKACCOUNT.FIRSTOWNERSFULLNAME = FIRSTOWNERSNAME,
BANKACCOUNT.SECONDOWNERSFULLNAME = SECONDOWNERSNAME,
BANKACCOUNT.ACCOUNTTYPE = ACCTYPE,
BANKACCOUNT.ACCOUNTSTATUS = STATUS,
BANKACCOUNT.JOINTOWNER = JOINT
WHERE BANKACCOUNT.ACCOUNTNUMBER = ACCNUM;
COMMIT;
END;
/

CREATE SEQUENCE ACC_NUM_GEN
MINVALUE 1000
MAXVALUE 3000
START WITH 1000
INCREMENT BY 1
CACHE 5;


CREATE TABLE USERS(
LOGINNAME VARCHAR2(14) PRIMARY KEY,
PASSWORD VARCHAR2(14),
FULLNAME VARCHAR(24),
PERMISSIONS VARCHAR2(30)
);

CREATE OR REPLACE PROCEDURE INSERTUSERS
(INLOGINNAME VARCHAR2,
INPASSWORD VARCHAR2,
INFULLNAME VARCHAR2,
INPERMISSIONS VARCHAR2
)
AS
BEGIN
INSERT INTO USERS VALUES(INLOGINNAME, INPASSWORD, INFULLNAME, INPERMISSIONS);
COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATEUSERS
(INLOGINNAME VARCHAR2,
INPASSWORD VARCHAR2,
INFULLNAME VARCHAR2,
INPERMISSIONS VARCHAR2
)
AS
BEGIN
UPDATE USERS
SET
USERS.FULLNAME = INFULLNAME,
USERS.PASSWORD = INPASSWORD,
USERS.PERMISSIONS = INPERMISSIONS
WHERE USERS.LOGINNAME = INLOGINNAME;
COMMIT;
END;
/

INSERT INTO USERS VALUES('admin','pass','admin','Admin');
INSERT INTO USERS VALUES('employee','pass','employee','Employee');
COMMIT;