CREATE SEQUENCE USER_ID;
--DROP SEQUENCE USER_ID;

CREATE SEQUENCE BANK_ACCOUNT_ID
START WITH 1000
INCREMENT BY 111
NOCACHE
NOCYCLE;

--DROP SEQUENCE BANK_ACCOUNT_ID;

CREATE TABLE BANK_USER(
USERID INT PRIMARY KEY,
FIRSTNAME VARCHAR2(50),
LASTNAME VARCHAR2(50),
USERNAME VARCHAR2(50),
PASSWORD VARCHAR2(50),
ACCOUNTID INTEGER
);

--DROP TABLE BANK_USER;

CREATE TABLE BANK_ACCOUNTS(
ACCOUNTID INTEGER PRIMARY KEY,
FIRSTNAME VARCHAR2(50),
LASTNAME VARCHAR2(50),
BALANCE FLOAT
);

ALTER TABLE BANK_ACCOUNTS
ADD CONSTRAINT FK_ACCOUNT_ID
FOREIGN KEY (ACCOUNTID) REFERENCES BANK_USER(ACCOUNTID);

--SELECT * FROM BANK_ACCOUNTS;
--DROP TABLE BANK_ACCOUNTS;

--PROCEDURE TO CREATE NEW ACCOUNTS (USER ACTION)
CREATE OR REPLACE PROCEDURE CREATE_ACCOUNT
(USERID IN NUMBER, FIRSTNAME IN VARCHAR2, LASTNAME IN VARCHAR2, BALANCE IN FLOAT)
AS
BEGIN
    INSERT INTO BANK_ACCOUNTS VALUES 
    (USERID, FIRSTNAME, LASTNAME, BANK_ACCOUNT_ID.NEXTVAL, BALANCE);
    COMMIT;
END;
/

--DROP PROCEDURE CREATE_ACCOUNT;

--PROCEDURE TO DELETE USER BANK ACCOUNT(USER ACTION)
CREATE OR REPLACE PROCEDURE DELETE_ACCOUNT(ACCOUNTID IN NUMBER)
AS
BEGIN
    DELETE FROM BANK_ACCOUNTS
    WHERE ACCOUNTID = ACCOUNT_ID;
COMMIT;
END;
/

--DROP PROCEDURE DELETE_ACCOUNT;

--DELETE USER (ADMIN ACTION)
CREATE OR REPLACE PROCEDURE DELETEUSER
(USER_ID IN NUMBER)
AS
BEGIN
    DELETE FROM BANK_USER
    WHERE USER_ID = USERID;
    DELETE FROM BANK_ACCOUNTS
    WHERE USER_ID = USERID;
    COMMIT;
END;
/

--DROP PROCEDURE DELETEUSER;