CREATE TABLE CUSTOMER_ACCOUNT (
    USER_ID INTEGER PRIMARY KEY,
    USERNAME VARCHAR2(100) UNIQUE,
    PASSWORD VARCHAR2(100),
    FIRSTNAME VARCHAR2(100),
    LASTNAME VARCHAR2(100)
);

CREATE TABLE BANK_ACCOUNT (
    BANK_ACCOUNT_ID INTEGER PRIMARY KEY,
    BALANCE FLOAT DEFAULT 0.0,
    USER_ID INTEGER
);

ALTER TABLE BANK_ACCOUNT
ADD CONSTRAINT FK_USER_ID
FOREIGN KEY (USER_ID) REFERENCES CUSTOMER_ACCOUNT(USER_ID);

CREATE SEQUENCE USERSEQ
MINVALUE 1000
MAXVALUE 2000
INCREMENT BY 1
CACHE 5;

CREATE SEQUENCE BANKSEQ
MINVALUE 1000
MAXVALUE 2000
INCREMENT BY 1
CACHE 5;

--INSERT INTO CUSTOMER
CREATE OR REPLACE PROCEDURE INSERTCUSTOMER
(USERNAME IN VARCHAR2, PASSWORD IN VARCHAR2, 
FIRSTNAME IN VARCHAR2, LASTNAME IN VARCHAR2)
AS
BEGIN
    INSERT INTO CUSTOMER_ACCOUNT VALUES 
    (USERSEQ.NEXTVAL, USERNAME, PASSWORD, FIRSTNAME, LASTNAME);
    COMMIT;
END;
/

--DELETE FROM CUSTOMER
CREATE OR REPLACE PROCEDURE DELETECUSTOMER
(CUSTOMER_ID IN NUMBER)
AS
BEGIN
    DELETE FROM BANK_ACCOUNT
    WHERE USER_ID = CUSTOMER_ID;
    DELETE FROM CUSTOMER_ACCOUNT
    WHERE USER_ID = CUSTOMER_ID;
    COMMIT;
END;
/

--UPDATE CUSTOMER
CREATE OR REPLACE PROCEDURE UPDATECUSTOMER
(ID IN NUMBER, USER IN VARCHAR2, PASS IN VARCHAR2, 
FIRST IN VARCHAR2, LAST IN VARCHAR2)
AS
BEGIN
    UPDATE CUSTOMER_ACCOUNT
    SET USERNAME = USER, PASSWORD = PASS,
    FIRSTNAME = FIRST, LASTNAME = LAST 
    WHERE USER_ID = ID;
    COMMIT;
END;
/

--INSERT INTO BANK
CREATE OR REPLACE PROCEDURE INSERTBANK
(ID IN NUMBER, BALANCE IN FLOAT, USER_ID IN NUMBER)
AS
BEGIN
    INSERT INTO BANK_ACCOUNT VALUES 
    (BANKSEQ.NEXTVAL, BALANCE, USER_ID);
    COMMIT;
END;
/

--DELETE FROM BANK
CREATE OR REPLACE PROCEDURE DELETEBANK
(BANK_ID IN NUMBER)
AS
BEGIN
    DELETE FROM BANK_ACCOUNT
    WHERE BANK_ID = BANK_ACCOUNT_ID;
    COMMIT;
END;
/

--UPDATE BANK
CREATE OR REPLACE PROCEDURE UPDATEBANK
(ID IN NUMBER, BAL IN FLOAT, UID IN NUMBER)
AS
BEGIN
    UPDATE BANK_ACCOUNT
    SET BALANCE = BAL, USER_ID = UID 
    WHERE BANK_ACCOUNT_ID = ID;
    COMMIT;
END;
/

SELECT * FROM BANK_ACCOUNT;
SELECT * FROM BANK_ACCOUNT
JOIN CUSTOMER_ACCOUNT
ON CUSTOMER_ACCOUNT.USER_ID = BANK_ACCOUNT.USER_ID
WHERE BANK_ACCOUNT.USER_ID = 1081;
