CREATE TABLE USERS
(
    USERID INTEGER PRIMARY KEY NOT NULL,
    FIRSTNAME VARCHAR2(20) NOT NULL,
    LASTNAME VARCHAR2(20) NOT NULL,
    USERNAME VARCHAR2(20) NOT NULL,
    PASSWORD VARCHAR2(20) NOT NULL
);
CREATE TABLE BANK_ACCOUNT
(
    BANK_ACCOUNTID INTEGER PRIMARY KEY,
    BALANCE FLOAT DEFAULT 0.00,
    USERID INTEGER NOT NULL,
    
    CONSTRAINT USERID_FK 
    FOREIGN KEY (USERID) 
    REFERENCES USERS(USERID)
);
CREATE TABLE ACCOUNT_TRANSACTIONS
(
    TRANSACTIONID INTEGER PRIMARY KEY,
    TRANSACTIONTYPE VARCHAR2(20) NOT NULL,
    AMOUNT FLOAT NOT NULL,
    USERID INTEGER NOT NULL,
    BANK_ACCOUNTID INTEGER NOT NULL,
    
    CONSTRAINT BANK_ACCOUNTID_FK
    FOREIGN KEY (BANK_ACCOUNTID)
    REFERENCES BANK_ACCOUNT(BANK_ACCOUNTID),
    
    CONSTRAINT USER_TRANID_FK
    FOREIGN KEY (USERID)
    REFERENCES USERS(USERID)
);


--DROP TABLE USERS;
--DROP TABLE BANK_ACCOUNT;
DROP TABLE ACCOUNT_TRANSACTIONS;

CREATE SEQUENCE USERSEQ;
CREATE SEQUENCE BANKACCOUNTSEQ;
CREATE SEQUENCE TRANSACTIONSEQ;

CREATE OR REPLACE PROCEDURE INSERTUSER
(FIRST_NAME IN VARCHAR2, LAST_NAME IN VARCHAR2,
USER_NAME IN VARCHAR2, PASS_WORD IN VARCHAR2)
AS
BEGIN
INSERT INTO USERS VALUES(USERSEQ.NEXTVAL, FIRST_NAME, LAST_NAME, USER_NAME, PASS_WORD);
END;
/
CREATE OR REPLACE PROCEDURE INSERTBANKACCOUNT
(USER_ID INTEGER)
AS
BEGIN
INSERT INTO BANK_ACCOUNT 
VALUES(BANKACCOUNTSEQ.NEXTVAL, 0.00, USER_ID);
END;
/
CREATE OR REPLACE PROCEDURE DELETEUSER
(USER_NAME IN VARCHAR2)
AS
BEGIN
DELETE FROM USERS WHERE USERNAME = USER_NAME;
END;
/
CREATE OR REPLACE PROCEDURE DELETEBANKACCOUNT
(ACCOUNTID IN INTEGER)
AS
BEGIN
DELETE FROM BANK_ACCOUNT WHERE BANK_ACCOUNTID = ACCOUNTID;
END;
/

CREATE OR REPLACE PROCEDURE UPDATEUSER
(USER_ID IN INTEGER, FIRST_NAME IN VARCHAR2, LAST_NAME IN VARCHAR2,
USER_NAME IN VARCHAR2, PASS_WORD IN VARCHAR2)
AS
BEGIN
    UPDATE USERS SET FIRSTNAME = FIRST_NAME WHERE USERID = USER_ID;
    UPDATE USERS SET LASTNAME = LAST_NAME WHERE USERID = USER_ID;
    UPDATE USERS SET USERNAME = USER_NAME WHERE USERID = USER_ID;
    UPDATE USERS SET PASSWORD = PASS_WORD WHERE USERID = USER_ID;
END;
/
CREATE OR REPLACE PROCEDURE UPDATEBANKACCOUNT
(ACCOUNT_ID IN INTEGER, BALANCE_ IN FLOAT, USER_ID IN INTEGER)
AS
BEGIN
    UPDATE BANK_ACCOUNT SET BALANCE = BALANCE_ WHERE BANK_ACCOUNTID = ACCOUNT_ID;
    UPDATE BANK_ACCOUNT SET USERID = USER_ID WHERE BANK_ACCOUNTID = ACCOUNT_ID;
END;
/
CREATE OR REPLACE PROCEDURE ADDTRANSACTION
(TRANSACTION_TYPE IN VARCHAR2, AMOUNT IN FLOAT, USERID IN INTEGER, BANKACCOUNTID IN INTEGER)
AS
BEGIN
    INSERT INTO ACCOUNT_TRANSACTIONS
    VALUES(TRANSACTIONSEQ.NEXTVAL, TRANSACTION_TYPE, AMOUNT, USERID, BANKACCOUNTID);
END;
/



CREATE OR REPLACE TRIGGER T_BEFOREUSERDELETE
BEFORE DELETE ON USERS
BEGIN
    DELETE FROM BANK_ACCOUNT B WHERE B.USERID = USERID;
END;
/
CREATE OR REPLACE TRIGGER T_BEFOREBANKACCOUNTDELETE
BEFORE DELETE ON BANK_ACCOUNT
BEGIN
    DELETE FROM ACCOUNT_TRANSACTIONS A WHERE A.BANK_ACCOUNTID = BANK_ACCOUNTID;
END;
/
COMMIT;