CREATE TABLE USERS
(
    USERID INTEGER PRIMARY KEY NOT NULL,
    FIRSTNAME VARCHAR2(20) NOT NULL,
    LASTNAME VARCHAR2(20) NOT NULL,
    USERNAME VARCHAR2(20) NOT NULL,
    PASSWORD VARCHAR2(20) NOT NULL
);
CREATE TABLE BANK_ACCOUNT
(
    BANK_ACCOUNTID INTEGER PRIMARY KEY NOT NULL,
    BALANCE FLOAT DEFAULT 0.00,
    USERID INTEGER NOT NULL,
    
    CONSTRAINT USERID_FK 
    FOREIGN KEY (USERID) 
    REFERENCES USERS(USERID)
);
--DROP TABLE USERS;
--DROP TABLE BANK_ACCOUNT;
--INSERT INTO USERS 
--(USERID, FIRSTNAME,LASTNAME,USERNAME, PASSWORD)
--VALUES
--(USERSEQ.NEXTVAL,'Nicholas','Low','nlow2492','wewe');
--COMMIT;

CREATE SEQUENCE USERSEQ;
CREATE SEQUENCE BANKACCOUNTSEQ;
COMMIT;


CREATE OR REPLACE PROCEDURE INSERTUSER
(FIRST_NAME IN VARCHAR2, LAST_NAME IN VARCHAR2,
USER_NAME IN VARCHAR2, PASS_WORD IN VARCHAR2)
AS
BEGIN
INSERT INTO USERS VALUES(USERSEQ.NEXTVAL, FIRST_NAME, LAST_NAME, USER_NAME, PASS_WORD);
END;
/
CREATE OR REPLACE PROCEDURE INSERTBANKACCOUNT
(USER_ID INTEGER)
AS
BEGIN
INSERT INTO BANK_ACCOUNT 
VALUES(BANKACCOUNTSEQ.NEXTVAL, 0.00, USER_ID);
END;
/
CREATE OR REPLACE PROCEDURE DELETEUSER
(USER_NAME IN VARCHAR2)
AS
BEGIN
DELETE FROM USERS WHERE USERNAME = USER_NAME;
END;
/
CREATE OR REPLACE PROCEDURE DELETEBANKACCOUNT
(ACCOUNTID IN INTEGER)
AS
BEGIN
DELETE FROM BANK_ACCOUNT WHERE BANK_ACCOUNTID = ACCOUNTID;
END;
/

CREATE OR REPLACE PROCEDURE UPDATEUSER
(USER_ID IN INTEGER, FIRST_NAME IN VARCHAR2, LAST_NAME IN VARCHAR2,
USER_NAME IN VARCHAR2, PASS_WORD IN VARCHAR2)
AS
BEGIN
    UPDATE USERS SET FIRSTNAME = FIRST_NAME WHERE USERID = USER_ID;
    UPDATE USERS SET LASTNAME = LAST_NAME WHERE USERID = USER_ID;
    UPDATE USERS SET USERNAME = USER_NAME WHERE USERID = USER_ID;
    UPDATE USERS SET PASSWORD = PASS_WORD WHERE USERID = USER_ID;
END;
/
CREATE OR REPLACE PROCEDURE UPDATEBANKACCOUNT
(ACCOUNT_ID IN INTEGER, BALANCE_ IN FLOAT, USER_ID IN INTEGER)
AS
BEGIN
    UPDATE BANK_ACCOUNT SET BALANCE = BALANCE_ WHERE BANK_ACCOUNTID = ACCOUNT_ID;
    UPDATE BANK_ACCOUNT SET USERID = USER_ID WHERE BANK_ACCOUNTID = ACCOUNT_ID;
END;
/

COMMIT;