--CREATE A SEQUENCE
CREATE SEQUENCE MYTESTSEQ
MINVALUE 600
MAXVALUE 900
INCREMENT BY 5
CACHE 5;
--USE THE SEQUENCE
SELECT MYTESTSEQ.NEXTVAL FROM DUAL;

INSERT INTO STUDENT(MYTESTSEQ.NEXTVAL, 'BOB');

--A VIEW TO A KILL
CREATE VIEW MYVIEW
AS SELECT TITLE FROM ALBUM
UNION
SELECT NAME FROM ARTIST;

--USE A VIEW
SELECT * FROM MYVIEW;
--CREATE A FUNCTION
CREATE OR REPLACE FUNCTION CALC_TAX
(T_ID IN NUMBER,TAX IN NUMBER)
RETURN NUMBER AS
TOTAL_PRICE NUMBER(10,2);
BEGIN
SELECT UNITPRICE INTO TOTAL_PRICE
FROM TRACK WHERE TRACKID= T_ID;
RETURN TOTAL_PRICE +(TOTAL_PRICE* TAX);
END;
/
--USE A FUNCTION
SELECT CALC_TAX(2921,.06) FROM DUAL;

--STORED PROCEDURE
CREATE OR REPLACE PROCEDURE MYFAKEPRO
( NAME IN VARCHAR2)
AS
BEGIN
INSERT INTO SCHOOL VALUES(MYSEQ.NEXTVAL,NAME);
COMMIT;
END;
/
--USE A STORED PROCEDURE
EXECUTE MYFAKEPRO('USF');

--MORE COMPLEX STORED PROCEDURE
CREATE OR REPLACE PROCEDURE BEARPRO
(CAVE_NAME IN VARCHAR2, BEAR_NAME IN vARCHAR2,
BEAR_BIRTHDATE IN DATE, CAVE_ID AS NUMBER)
AS
BEGIN
INSERT INTO CAVE VALUES(MYSEQ.NEXTVAL,CAVE_NAME);
INSERT INTO BEEHIVE VALUES(MYSEQ.NEXTVAL,50);
INSERT INTO BEAR VALUES( MYSEQ.NEXTVAL,1,BEAR_NAME,BEAR_BIRTHDATE,200,CAVE_ID);
COMMIT;
END;
/

EXECUTE BEARPRO('WOO','PERT',DATE '1999-02-15',1);
